export const VERIFY_USER_STATUS = {
  SUCCESS: 'SUCCESS',
  ALREADY_VERIFIED: 'ALREADY_VERIFIED',
  INVALID_OR_EXPIRED: 'INVALID_OR_EXPIRED',
} as const;
export type VerifyUserStatus =
  (typeof VERIFY_USER_STATUS)[keyof typeof VERIFY_USER_STATUS];
