export enum MailErrorCode {
  TEMPLATE_ERROR = 'TEMPLATE_ERROR',
  SERVER_ERROR = 'MAIL_SERVER_ERROR',
  INVALID_RECIPIENT = 'MAIL_INVALID_RECIPIENT',
  TIME_OUT = 'TIME_OUT',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
}
